### PR TITLE
Update all example notebooks

### PR DESCRIPTION
**Pull request by charlesreid1**
This pull request contains a substantial number of changes, but the substance of the notebooks has been preserved in each case. The main changes in this pull request are:
* trackpy now normalizes "mass" quantities, so several notebooks had to be updated to account for this
* added many more links to the trackpy and pims source code/documentation when relevant classes were mentioned
* removed some deprecated code (e.g., the now-deprecated `threshold_adaptive()` function in scikit-image) and updated mentions of old versions of software (e.g., ipython-parallel)

There are also cosmetic changes caused by changes to modules/libraries since the last time these notebooks were updated (e.g., output of `timeit` commands or ipython notebooks lacking a "collapsed" state).

Please comment on anything that you have doubts about or wish to discuss. When you're okay with these updates and they've been merged, I would also be happy to export them to HTML, add them to the [soft-matter.github.io trackpy page](https://soft-matter.github.io/trackpy/v0.3.2/), and send a pull request for that repo as well.

### CODE REVIEW

**Comment by charlesreid1** [comment]
This pull request will be updated as follows:
* Any notebook that uses mass values will have a text warning included, along the lines of "if scikit-image is not installed, pim will fall back to matplotlib for reading images, which causes pixel values to be read as floats and not integers, so you may not get sensible results," etc.
* The issue that I had originally brought up, regarding mass values and pixel values being normalized, was coming from pims and was caused by scikit-image not being installed, see soft-matter/pims#280
* This should now print a warning so that users without scikit-image installed will know that some things may break, and why

**Comment by charlesreid1** [comment]
Uncovered another issue while updating these notebooks - installing trackpy from pip implements a legacy `link_df()` interface, where there is a `diagnostics` parameter, but this interface breaks when using trackpy installed from the github repository. See #45 for proposed fix, implemented in this PR.

**Comment by danielballan** [comment]
Wow, thanks for taking the time for do this @charlesreid1. I appreciate the granular commits.

>  I would also be happy to export them to HTML, add them to the soft-matter.github.io trackpy page, and send a pull request for that repo as well.

The HTML will be automatically generated and push into the docs repo when this PR is merged, so no separate PR into the docs repo is needed. Thanks for the offer to present a more reviewable form. I'm content to build it locally and take a look. Will give this a detailed review today or tomorrow.

**Comment by danielballan** [comment]
So sorry for letting this languish so long, @charlesreid1. Merging!

**Comment by charlesreid1** [comment]
No problem. Thanks for the pull!

**Pull request merged**
