### PR TITLE
Updates for py2 and 3 compat, IPython 4

### PR DESCRIPTION
**Pull request by danielballan**
See commit messages for details. This confirms that parallelization works again on slicerator v0.9.3 and pims master (soon-to-be v0.3.0).

There is more updating to do in other notebooks

### CODE REVIEW

**Comment by tacaswell** [comment]
merge this as-is or hold off for other edits?

**Comment by nkeim** [comment]
Does this fail with older (but still recent) versions of pims?

If no, I say merge. This fixes some stumbling blocks that are annoying new users as we speak :wink:. And we should strongly consider tagging a v0.3.0 release of this repo.

**Comment by danielballan** [comment]
This has no changes to pims. Further fixes await my installing LaTeX on my new laptop so I can render the plots, haha.

Merge at will.

Tag v0.3.0 now, fix docs later? Fine by me if that's what the people want.

**Comment by nkeim** [comment]
OK. I'm thinking we should wait until we do a final build of the docs for trackpy v0.3.0 to tag this. Mostly for archaeological purposes.

**Pull request merged**
